/*
 * Copyright 2014-2015 CyberVision, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# ifndef KAA_DEFAULTS_H_
# define KAA_DEFAULTS_H_

/**
 *
 * DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED.
 *
 */

# include "kaa_common.h"

# ifdef __cplusplus
extern "C" {
# endif

# define BUILD_VERSION                  "0.7.3"
# define BUILD_COMMIT_HASH              ""

# define KAA_SDK_TOKEN                  "nQpZqhn8hy/z2Cy+iJ5XHO9IvM4="

# define PROFILE_SCHEMA_VERSION          2


# define KAA_SYNC_TIMEOUT               60000L


/**
 * @brief Uses to represent transport-specific connection data to establish
 * connection to Bootstrap servers.
 *
 * @see kaa_transport_protocol_id_t
 * @see kaa_access_point_t
 */
typedef struct {
    kaa_transport_protocol_id_t    protocol_id;
    kaa_access_point_t             access_point;
} kaa_bootstrap_server_connection_data_t;

# define KAA_BOOTSTRAP_ACCESS_POINT_COUNT    2

static const kaa_bootstrap_server_connection_data_t KAA_BOOTSTRAP_ACCESS_POINTS[KAA_BOOTSTRAP_ACCESS_POINT_COUNT] =
{
    {
        { 0xfb9a3cf0, 1 },
        {
            0x95f7e40f,
            319,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -102 , -90 , -115 , 48 , 9 , -67 , 112 , 120 , 19 , 96 , -106 , -65 , 77 , 108 , -56 , -28 , -112 , -82 , 113 , -36 , -49 , 26 , -73 , -121 , -71 , -121 , 116 , -58 , 30 , 122 , 1 , -72 , -113 , -9 , 91 , 53 , -118 , 99 , -8 , -100 , 13 , 10 , -26 , -40 , 69 , -19 , -97 , -72 , -113 , -65 , 83 , -128 , -20 , -121 , -34 , 124 , -57 , 87 , -52 , -25 , 96 , -62 , -63 , -71 , -81 , -20 , 47 , 57 , 75 , 71 , 3 , 86 , 36 , 125 , -56 , 18 , 21 , 74 , 59 , 18 , 81 , 42 , 72 , -9 , -98 , -75 , -46 , -21 , 16 , -3 , -106 , 58 , -31 , 99 , 103 , -18 , -112 , -51 , -77 , 116 , 28 , 65 , 42 , 17 , 111 , -99 , -94 , -35 , -56 , -10 , -123 , -41 , 0 , 113 , -47 , 2 , -55 , -25 , -12 , 60 , 57 , 24 , -33 , 45 , 84 , -12 , -70 , 9 , -46 , 55 , 107 , -115 , 11 , 120 , 5 , 77 , 125 , 8 , 106 , -90 , 53 , 81 , -115 , -51 , 27 , 42 , -118 , 55 , -79 , 97 , -92 , 46 , 26 , -99 , 81 , -121 , -59 , -79 , 27 , -29 , 55 , -110 , 98 , -21 , -113 , -63 , 114 , 86 , -96 , 27 , -1 , 99 , -54 , 9 , -47 , -124 , 56 , -92 , 120 , 76 , 61 , -84 , -58 , -13 , -105 , 97 , -65 , 9 , -37 , -90 , -101 , -81 , 5 , -32 , -122 , -40 , -58 , 78 , 108 , -101 , 105 , 104 , -6 , -104 , -87 , 105 , 116 , 75 , 11 , -55 , -73 , 36 , 101 , 34 , 42 , 120 , -86 , 23 , -11 , 67 , 91 , 121 , 125 , -117 , 108 , -111 , -14 , -72 , 99 , -60 , 67 , 5 , 16 , -44 , 71 , -6 , -1 , -34 , 57 , -21 , 86 , 56 , -91 , 85 , 38 , 92 , 20 , 25 , 114 , 123 , -89 , -93 , 46 , 4 , -69 , 21 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 13 , 53 , 50 , 46 , 51 , 50 , 46 , 50 , 48 , 55 , 46 , 49 , 57 , 52 , 0 , 0 , 38 , -95             }
        }
    },
    {
        { 0x56c8ff92, 1 },
        {
            0x95f7e40f,
            319,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -102 , -90 , -115 , 48 , 9 , -67 , 112 , 120 , 19 , 96 , -106 , -65 , 77 , 108 , -56 , -28 , -112 , -82 , 113 , -36 , -49 , 26 , -73 , -121 , -71 , -121 , 116 , -58 , 30 , 122 , 1 , -72 , -113 , -9 , 91 , 53 , -118 , 99 , -8 , -100 , 13 , 10 , -26 , -40 , 69 , -19 , -97 , -72 , -113 , -65 , 83 , -128 , -20 , -121 , -34 , 124 , -57 , 87 , -52 , -25 , 96 , -62 , -63 , -71 , -81 , -20 , 47 , 57 , 75 , 71 , 3 , 86 , 36 , 125 , -56 , 18 , 21 , 74 , 59 , 18 , 81 , 42 , 72 , -9 , -98 , -75 , -46 , -21 , 16 , -3 , -106 , 58 , -31 , 99 , 103 , -18 , -112 , -51 , -77 , 116 , 28 , 65 , 42 , 17 , 111 , -99 , -94 , -35 , -56 , -10 , -123 , -41 , 0 , 113 , -47 , 2 , -55 , -25 , -12 , 60 , 57 , 24 , -33 , 45 , 84 , -12 , -70 , 9 , -46 , 55 , 107 , -115 , 11 , 120 , 5 , 77 , 125 , 8 , 106 , -90 , 53 , 81 , -115 , -51 , 27 , 42 , -118 , 55 , -79 , 97 , -92 , 46 , 26 , -99 , 81 , -121 , -59 , -79 , 27 , -29 , 55 , -110 , 98 , -21 , -113 , -63 , 114 , 86 , -96 , 27 , -1 , 99 , -54 , 9 , -47 , -124 , 56 , -92 , 120 , 76 , 61 , -84 , -58 , -13 , -105 , 97 , -65 , 9 , -37 , -90 , -101 , -81 , 5 , -32 , -122 , -40 , -58 , 78 , 108 , -101 , 105 , 104 , -6 , -104 , -87 , 105 , 116 , 75 , 11 , -55 , -73 , 36 , 101 , 34 , 42 , 120 , -86 , 23 , -11 , 67 , 91 , 121 , 125 , -117 , 108 , -111 , -14 , -72 , 99 , -60 , 67 , 5 , 16 , -44 , 71 , -6 , -1 , -34 , 57 , -21 , 86 , 56 , -91 , 85 , 38 , 92 , 20 , 25 , 114 , 123 , -89 , -93 , 46 , 4 , -69 , 21 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 13 , 53 , 50 , 46 , 51 , 50 , 46 , 50 , 48 , 55 , 46 , 49 , 57 , 52 , 0 , 0 , 38 , -96             }
        }
    }};



# define KAA_CONFIGURATION_DATA_LENGTH    17

static const char KAA_CONFIGURATION_DATA[KAA_CONFIGURATION_DATA_LENGTH] =
{
0 , 4 , -125 , 24 , 106 , -91 , -87 , 66 , 122 , -100 , -27 , -18 , 99 , -60 , 36 , -80 , 50 };

# ifdef __cplusplus
} // extern "C"
# endif

# endif /* KAA_DEFAULTS_H_ */

