$(eval $(call PackageDir,cns21xx,cns21xx,))
$(eval $(call PackageDir,cns21xx_cobalt,cns21xx/cobalt,))
$(eval $(call PackageDir,cns21xx_sibyte,cns21xx/sibyte,))
$(eval $(call PackageDir,cns21xx_sparc,cns21xx/sparc,))
$(eval $(call PackageDir,ep93xx,ep93xx,))
$(eval $(call PackageDir,iop32x,iop32x,))
$(eval $(call PackageDir,mpc52xx,mpc52xx,))
$(eval $(call PackageDir,mpc83xx,mpc83xx,))
