#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=97

boot()
{
	mode=$(uci get modem.@modem[0].mode)
	module=$(uci get modem.@modem[0].module)
	if [[ "$module" == "MC7350" ]]; then
		exit 0
	else
		autoconnect=$(uci get modem.@modem[0].autoconnect)
		if [[ "$mode" == "Auto" ]]; then
			uqmi -d /dev/cdc-wdm0 --set-network-modes all
		elif [[ "$mode" == "LTE" ]]; then
			uqmi -d /dev/cdc-wdm0 --set-network-modes lte
		elif [[ "$mode" == "3G" ]]; then
			uqmi -d /dev/cdc-wdm0 --set-network-modes umts
		fi
		
		if [[ "$autoconnect" == "1" ]]; then
			uqmi -d /dev/cdc-wdm0 --stop-network 0xffffffff --autoconnect
			uqmi -d /dev/cdc-wdm0 --start-network internet --autoconnect
#			udhcpc -i wwan0 -p /var/run/udhcpc-wwan0.pid
		else
			uqmi -d /dev/cdc-wdm0 --stop-network 0xffffffff --autoconnect
		fi
                # if we start network via uqmi, it seems improperly reset the route table
                # and would cause mwan3 to not able to keep track of the cell connection, reset the all network
                # interfaces allow mwan to keep track of all connections again.
                sleep 10;
                /etc/init.d/network restart
	fi
	
}
