#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=96
STOP=98

boot() {
	module=$(at.sh AT+GMM | awk '{print $1}')
	uci set modem.@modem[0].module=$module
	if [[ "$module" == "MC7350" ]]; then
		uci set system.@system[0].hostname="ER1000-VZ"
	elif [[ "$module" == "LE910-EUG" ]]; then
		uci set system.@system[0].hostname="ER1000T-EU"
	else
		uci set system.@system[0].hostname="ER1000T-NA"
	fi
	uci commit
	/etc/init.d/system restart
}


stop() {
        module=$(uci get system.@system[0].hostname)
        if [ "$module" == "ER1000-VZ" ]; then
                at.sh "at!reset"
        fi
}
